services:
  # =========================
  # PostgreSQL for UserService
  # =========================
  postgres-user:
    image: postgres:15-alpine
    container_name: postgres_user_service
    restart: always
    environment:
      POSTGRES_USER: event_user
      POSTGRES_PASSWORD: event_pass
      POSTGRES_DB: userdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_user_data:/var/lib/postgresql/data
    networks:
      - event-network

  # =========================
  # pgAdmin
  # =========================
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"                  # UI web
    depends_on:
      - postgres-user
    networks:
      - event-network

  # =========================
  # MySQL for Keycloak
  # =========================
  keycloak-mysql:
    container_name: keycloak-mysql
    image: mysql:8
    volumes:
      - ./volume-data/mysql_keycloak_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: keycloak
      MYSQL_USER: keycloak
      MYSQL_PASSWORD: password

  # =========================
  # MySQL for Keycloak
  # =========================
  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:24.0.1
    command: [ "start-dev", "--import-realm" ]
    environment:
      DB_VENDOR: MYSQL
      DB_ADDR: mysql
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_PASSWORD: password
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8090:8080"
    volumes:
      - ./docker/keycloak/realms/:/opt/keycloak/data/import/
    depends_on:
      - keycloak-mysql

# -------------------------
# Common Network
# -------------------------
networks:
  event-network:
    driver: bridge



